// Mocks generated by Mockito 5.4.6 from annotations
// in timelyst_flutter/test/unit/calendar_sync_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:timelyst_flutter/models/calendars.dart' as _i2;
import 'package:timelyst_flutter/services/googleIntegration/googleCalendarService.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCalendarDelta_0 extends _i1.SmartFake implements _i2.CalendarDelta {
  _FakeCalendarDelta_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCalendarPage_1 extends _i1.SmartFake implements _i2.CalendarPage {
  _FakeCalendarPage_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GoogleCalendarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleCalendarService extends _i1.Mock
    implements _i3.GoogleCalendarService {
  MockGoogleCalendarService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.CalendarDelta> fetchCalendarChanges({
    required String? userId,
    required String? email,
    required String? syncToken,
    int? maxResults = 250,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCalendarChanges,
          [],
          {
            #userId: userId,
            #email: email,
            #syncToken: syncToken,
            #maxResults: maxResults,
          },
        ),
        returnValue: _i4.Future<_i2.CalendarDelta>.value(_FakeCalendarDelta_0(
          this,
          Invocation.method(
            #fetchCalendarChanges,
            [],
            {
              #userId: userId,
              #email: email,
              #syncToken: syncToken,
              #maxResults: maxResults,
            },
          ),
        )),
      ) as _i4.Future<_i2.CalendarDelta>);

  @override
  _i4.Future<void> saveCalendarsBatch({
    required String? userId,
    required String? email,
    required List<_i2.Calendar>? calendars,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCalendarsBatch,
          [],
          {
            #userId: userId,
            #email: email,
            #calendars: calendars,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.CalendarPage> fetchCalendarsPage({
    required String? userId,
    required String? email,
    String? pageToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCalendarsPage,
          [],
          {
            #userId: userId,
            #email: email,
            #pageToken: pageToken,
          },
        ),
        returnValue: _i4.Future<_i2.CalendarPage>.value(_FakeCalendarPage_1(
          this,
          Invocation.method(
            #fetchCalendarsPage,
            [],
            {
              #userId: userId,
              #email: email,
              #pageToken: pageToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.CalendarPage>);
}
