// // Mocks generated by Mockito 5.4.4 from annotations
// // in timelyst_flutter/test/unit/apis/googleIntegration/googleSignInOut_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i5;

// import 'package:google_sign_in/google_sign_in.dart' as _i3;
// import 'package:google_sign_in/src/token_types.dart' as _i2;
// import 'package:mockito/mockito.dart' as _i1;
// import 'package:mockito/src/dummies.dart' as _i6;
// import 'package:timelyst_flutter/apis/googleIntegration/googleAuthService.dart'
//     as _i4;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// class _FakeGoogleSignInAuthentication_0 extends _i1.SmartFake
//     implements _i2.GoogleSignInAuthentication {
//   _FakeGoogleSignInAuthentication_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeGoogleSignInAuthorizationClient_1 extends _i1.SmartFake
//     implements _i3.GoogleSignInAuthorizationClient {
//   _FakeGoogleSignInAuthorizationClient_1(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeGoogleSignInClientAuthorization_2 extends _i1.SmartFake
//     implements _i2.GoogleSignInClientAuthorization {
//   _FakeGoogleSignInClientAuthorization_2(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// /// A class which mocks [GoogleAuthService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockGoogleAuthService extends _i1.Mock implements _i4.GoogleAuthService {
//   MockGoogleAuthService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i5.Future<Map<String, dynamic>> sendAuthCodeToBackend(String? authCode) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #sendAuthCodeToBackend,
//           [authCode],
//         ),
//         returnValue:
//             _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
//       ) as _i5.Future<Map<String, dynamic>>);
// }

// /// A class which mocks [GoogleSignInAccount].
// ///
// /// See the documentation for Mockito's code generation for more information.
// // ignore: must_be_immutable
// class MockGoogleSignInAccount extends _i1.Mock
//     implements _i3.GoogleSignInAccount {
//   MockGoogleSignInAccount() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   String get email => (super.noSuchMethod(
//         Invocation.getter(#email),
//         returnValue: _i6.dummyValue<String>(
//           this,
//           Invocation.getter(#email),
//         ),
//       ) as String);

//   @override
//   String get id => (super.noSuchMethod(
//         Invocation.getter(#id),
//         returnValue: _i6.dummyValue<String>(
//           this,
//           Invocation.getter(#id),
//         ),
//       ) as String);

//   @override
//   _i2.GoogleSignInAuthentication get authentication => (super.noSuchMethod(
//         Invocation.getter(#authentication),
//         returnValue: _FakeGoogleSignInAuthentication_0(
//           this,
//           Invocation.getter(#authentication),
//         ),
//       ) as _i2.GoogleSignInAuthentication);

//   @override
//   _i3.GoogleSignInAuthorizationClient get authorizationClient =>
//       (super.noSuchMethod(
//         Invocation.getter(#authorizationClient),
//         returnValue: _FakeGoogleSignInAuthorizationClient_1(
//           this,
//           Invocation.getter(#authorizationClient),
//         ),
//       ) as _i3.GoogleSignInAuthorizationClient);
// }

// /// A class which mocks [GoogleSignInAuthorizationClient].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockGoogleSignInAuthorizationClient extends _i1.Mock
//     implements _i3.GoogleSignInAuthorizationClient {
//   MockGoogleSignInAuthorizationClient() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i5.Future<_i2.GoogleSignInClientAuthorization?> authorizationForScopes(
//           List<String>? scopes) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #authorizationForScopes,
//           [scopes],
//         ),
//         returnValue: _i5.Future<_i2.GoogleSignInClientAuthorization?>.value(),
//       ) as _i5.Future<_i2.GoogleSignInClientAuthorization?>);

//   @override
//   _i5.Future<_i2.GoogleSignInClientAuthorization> authorizeScopes(
//           List<String>? scopes) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #authorizeScopes,
//           [scopes],
//         ),
//         returnValue: _i5.Future<_i2.GoogleSignInClientAuthorization>.value(
//             _FakeGoogleSignInClientAuthorization_2(
//           this,
//           Invocation.method(
//             #authorizeScopes,
//             [scopes],
//           ),
//         )),
//       ) as _i5.Future<_i2.GoogleSignInClientAuthorization>);

//   @override
//   _i5.Future<Map<String, String>?> authorizationHeaders(
//     List<String>? scopes, {
//     bool? promptIfNecessary = false,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #authorizationHeaders,
//           [scopes],
//           {#promptIfNecessary: promptIfNecessary},
//         ),
//         returnValue: _i5.Future<Map<String, String>?>.value(),
//       ) as _i5.Future<Map<String, String>?>);

//   @override
//   _i5.Future<_i2.GoogleSignInServerAuthorization?> authorizeServer(
//           List<String>? scopes) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #authorizeServer,
//           [scopes],
//         ),
//         returnValue: _i5.Future<_i2.GoogleSignInServerAuthorization?>.value(),
//       ) as _i5.Future<_i2.GoogleSignInServerAuthorization?>);
// }
