// Mocks generated by Mockito 5.4.6 from annotations
// in timelyst_flutter/test/unit/google_sign_in_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:timelyst_flutter/services/googleIntegration/google_sign_in_result.dart'
    as _i2;
import 'package:timelyst_flutter/services/googleIntegration/googleSignInOut.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGoogleSignInResult_0 extends _i1.SmartFake
    implements _i2.GoogleSignInResult {
  _FakeGoogleSignInResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GoogleSignInOutService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInOutService extends _i1.Mock
    implements _i3.GoogleSignInOutService {
  MockGoogleSignInOutService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GoogleSignInResult> googleSignIn(String? serverAuthCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #googleSignIn,
          [serverAuthCode],
        ),
        returnValue:
            _i4.Future<_i2.GoogleSignInResult>.value(_FakeGoogleSignInResult_0(
          this,
          Invocation.method(
            #googleSignIn,
            [serverAuthCode],
          ),
        )),
      ) as _i4.Future<_i2.GoogleSignInResult>);

  @override
  _i4.Future<void> googleDisconnect() => (super.noSuchMethod(
        Invocation.method(
          #googleDisconnect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> googleSignOut() => (super.noSuchMethod(
        Invocation.method(
          #googleSignOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
