// // Mocks generated by Mockito 5.4.4 from annotations
// // in timelyst_flutter/test/unit/apis/googleIntegration/googleOrchestrator_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i4;

// import 'package:flutter/material.dart' as _i6;
// import 'package:google_sign_in/google_sign_in.dart' as _i5;
// import 'package:mockito/mockito.dart' as _i1;
// import 'package:timelyst_flutter/apis/googleIntegration/googleCalendarService.dart'
//     as _i2;
// import 'package:timelyst_flutter/apis/googleIntegration/googleSignInOut.dart'
//     as _i3;
// import 'package:timelyst_flutter/models/calendars.dart' as _i7;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// class _FakeCalendarPage_0 extends _i1.SmartFake implements _i2.CalendarPage {
//   _FakeCalendarPage_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeCalendarDelta_1 extends _i1.SmartFake implements _i2.CalendarDelta {
//   _FakeCalendarDelta_1(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// /// A class which mocks [GoogleSignInOutService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockGoogleSignInOutService extends _i1.Mock
//     implements _i3.GoogleSignInOutService {
//   MockGoogleSignInOutService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i4.Stream<_i5.GoogleSignInAccount?> get onCurrentUserChanged =>
//       (super.noSuchMethod(
//         Invocation.getter(#onCurrentUserChanged),
//         returnValue: _i4.Stream<_i5.GoogleSignInAccount?>.empty(),
//       ) as _i4.Stream<_i5.GoogleSignInAccount?>);

//   @override
//   _i4.Future<void> initialize() => (super.noSuchMethod(
//         Invocation.method(
//           #initialize,
//           [],
//         ),
//         returnValue: _i4.Future<void>.value(),
//         returnValueForMissingStub: _i4.Future<void>.value(),
//       ) as _i4.Future<void>);

//   @override
//   _i4.Future<Map<String, dynamic>> googleSignIn(_i6.BuildContext? context) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #googleSignIn,
//           [context],
//         ),
//         returnValue:
//             _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
//       ) as _i4.Future<Map<String, dynamic>>);

//   @override
//   _i4.Future<void> googleSignOut() => (super.noSuchMethod(
//         Invocation.method(
//           #googleSignOut,
//           [],
//         ),
//         returnValue: _i4.Future<void>.value(),
//         returnValueForMissingStub: _i4.Future<void>.value(),
//       ) as _i4.Future<void>);

//   @override
//   bool isUserSignedIn() => (super.noSuchMethod(
//         Invocation.method(
//           #isUserSignedIn,
//           [],
//         ),
//         returnValue: false,
//       ) as bool);
// }

// /// A class which mocks [GoogleCalendarService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockGoogleCalendarService extends _i1.Mock
//     implements _i2.GoogleCalendarService {
//   MockGoogleCalendarService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i4.Future<_i2.CalendarPage> fetchCalendarsPage({
//     required String? userId,
//     required String? email,
//     int? pageSize = 50,
//     String? pageToken,
//     DateTime? modifiedSince,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #fetchCalendarsPage,
//           [],
//           {
//             #userId: userId,
//             #email: email,
//             #pageSize: pageSize,
//             #pageToken: pageToken,
//             #modifiedSince: modifiedSince,
//           },
//         ),
//         returnValue: _i4.Future<_i2.CalendarPage>.value(_FakeCalendarPage_0(
//           this,
//           Invocation.method(
//             #fetchCalendarsPage,
//             [],
//             {
//               #userId: userId,
//               #email: email,
//               #pageSize: pageSize,
//               #pageToken: pageToken,
//               #modifiedSince: modifiedSince,
//             },
//           ),
//         )),
//       ) as _i4.Future<_i2.CalendarPage>);

//   @override
//   _i4.Future<_i2.CalendarDelta> fetchCalendarChanges({
//     required String? userId,
//     required String? email,
//     required String? syncToken,
//     int? maxResults = 250,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #fetchCalendarChanges,
//           [],
//           {
//             #userId: userId,
//             #email: email,
//             #syncToken: syncToken,
//             #maxResults: maxResults,
//           },
//         ),
//         returnValue: _i4.Future<_i2.CalendarDelta>.value(_FakeCalendarDelta_1(
//           this,
//           Invocation.method(
//             #fetchCalendarChanges,
//             [],
//             {
//               #userId: userId,
//               #email: email,
//               #syncToken: syncToken,
//               #maxResults: maxResults,
//             },
//           ),
//         )),
//       ) as _i4.Future<_i2.CalendarDelta>);

//   @override
//   _i4.Future<void> saveCalendarsBatch({
//     required String? userId,
//     required String? email,
//     required List<_i7.Calendar>? calendars,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #saveCalendarsBatch,
//           [],
//           {
//             #userId: userId,
//             #email: email,
//             #calendars: calendars,
//           },
//         ),
//         returnValue: _i4.Future<void>.value(),
//         returnValueForMissingStub: _i4.Future<void>.value(),
//       ) as _i4.Future<void>);
// }
